<?php include("db.php");?>  <!-- Login Session and database functions -->
<?php include("header.php");?>  <!-- Header. Replace if you want to customize -->
<?php include("menubar.php");?>  <!-- Common top menu bar -->

<html>
<style>
body, html {
  height: 100%;
  margin: 0;
}

.transbox {
  width: 100px;
  padding: 60px;
  margin: 60px;
  background-color: #ffffff;
  border: 2px solid black;
  opacity: 1.0;
}

.transbox p {
  margin: 10%;
  font-weight: bold;
  color: #000000;
}

.middle {
  position: absolute;
  top: 40%;
  left: 80%;
  margin: 25%;
  transform: translate(-50%, -50%);
  text-align: justify;
  text-justify: inter-word;
}

hr {
  margin: auto;
  width: 60%;
}

#splash {
padding: 40px;
position: relative;
background: #FFF;
margin: 20px 0 0 0;
height: 300px;
width: 1100px;
box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.25);
}

.post {
width: 1000px;
margin-left: auto ;
margin-right: auto ;
}

.post {
width: 1000px;
margin-left: auto ;
margin-right: auto ;
}

p {
margin-bottom: 1.75em;
margin-left: auto ;
margin-right: auto ;    
}

</style>
<body>
  
<!-- <div id="splash"> -->
<div id="transbox">
    <div class="post">
<p><img src="pq/quest_flowers.png" width="1000px" height="700px" /></p>
    </div>
</div>

<div id="transbox">
    <div class="post2">
        
<!-- Image Map Generated by http://www.image-map.net/ -->
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://1.bp.blogspot.com/-2pmxfTNrLXg/Xy-gJJsRC1I/AAAAAAAAAcI/Y5AOdRyVKxQ7BMT4EETsJmqafcRhonI8ACLcBGAsYHQ/s2048/hidden.jpg" usemap="#image-map">

<map name="image-map">
    <area target="_blank" alt="u better get this one" title="u better get this one" href="https://1.bp.blogspot.com/-4lJyDSGZSgM/Xy-enR4XxyI/AAAAAAAAAbQ/ZklNfyWDZ1sSmFISrkQTBSHXqXNkf6L_gCLcBGAsYHQ/s2511/a%2Bclassic.jpg" coords="1275,1347,79" shape="circle">
    <area target="_blank" alt="good luck with that" title="good luck with that" href="https://1.bp.blogspot.com/-5t_bWUGeero/Xy-ezwyIz8I/AAAAAAAAAbU/c2g_XFB3Ozor2ZrIYbcfRm_oYl2wYY5rACLcBGAsYHQ/s1098/insert%2Bflower%2Bname.jpg" coords="1990,96,67" shape="circle">
    <area target="_blank" alt="you'll figure it out" title="you'll figure it out" href="https://1.bp.blogspot.com/-40llUVdNlaY/Xy-e8gNOJzI/AAAAAAAAAbc/7L090nmzzLM2XcqvFVji6FsRhp2wzOb6wCLcBGAsYHQ/s886/figure%2Bit%2Bout.jpg" coords="49,894,56" shape="circle">
    <area target="_blank" alt="no hints here, bub" title="no hints here, bub" href="https://1.bp.blogspot.com/-S6zEMMmJyiI/Xy-fK7tSWPI/AAAAAAAAAbk/-Iemi4I0I0Emo-zAwwMSscyO3nyNGJGyQCLcBGAsYHQ/s800/no%2Bhints%2Bfor%2Byou.jpg" coords="371,219,56" shape="circle">
    <area target="_blank" alt="that's poppin'" title="that's poppin'" href="https://1.bp.blogspot.com/-cWUZsbrU4z0/Xy-ffp_qOtI/AAAAAAAAAb0/EXBIJPNPVKYIRffR4hhOvewli7OMDms8ACLcBGAsYHQ/s500/poppin.jpg" coords="666,317,49" shape="circle">
    <area target="_blank" alt="what r u" title="what r u" href="https://1.bp.blogspot.com/-I0wO3zZey4A/Xy-fqB3DvdI/AAAAAAAAAb8/Clm9e5oNPIg57uRc8G5FHUuaFX0cI1NAACLcBGAsYHQ/s1080/a%2Bnice%2Bblue.jpg" coords="744,557,51" shape="circle">
    <area target="_blank" alt="if popcorn was a flower" title="if popcorn was a flower" href="https://1.bp.blogspot.com/-RMB_DzNJ0bA/Xy-h36I8K7I/AAAAAAAAAcU/YLsH20KQZdIDVs70PncKUoLLsKve5wHTACLcBGAsYHQ/s0/popcorn%2Btbh.jpg" coords="25,201,65" shape="circle">
    <area target="_blank" alt="ohlala, so beau" title="ohlala, so beau" href="https://1.bp.blogspot.com/-vIldd-SQ4hA/Xy-iITQHE6I/AAAAAAAAAcc/W_Ii4GE3D1wZFlYlfdx0d5WDrIQl9mkRgCLcBGAsYHQ/s600/so%2Bbeau.jpg" coords="458,362,48" shape="circle">
    <area target="_blank" alt="omg so lush" title="omg so lush" href="https://1.bp.blogspot.com/-zyWP5HzVZq0/Xy-iaLXfLcI/AAAAAAAAAck/GQphHW_y3q4F87gjNSYZ3iiTfvFxgawAACLcBGAsYHQ/s1483/so%2Blush.jpg" coords="1591,71,87" shape="circle">
    <area target="_blank" alt="our spidey senses are tingling .." title="our spidey senses are tingling .." href="https://1.bp.blogspot.com/-Ky9SuTemwl4/Xy-iguW6rOI/AAAAAAAAAco/r55p7SrrJaYqrn30vfHT6oL1vcd1MuZOgCLcBGAsYHQ/s784/spook%2Bspook.jpg" coords="2019,905,63" shape="circle">
    <area target="_blank" alt="fuckin fab" title="fuckin fab" href="https://1.bp.blogspot.com/-NCvr1Uja6Ro/Xy-ix2yockI/AAAAAAAAAdA/zawqY2pLzxg60A8pw8q76sIYT3I83sxaACLcBGAsYHQ/s1200/fuckin%2Bfab.jpg" coords="1985,1191,63" shape="circle">
    <area target="_blank" alt="that's a sweet ass flower" title="that's a sweet ass flower" href="https://1.bp.blogspot.com/-fPnf0r9LtVA/Xy-i1p-TQsI/AAAAAAAAAdE/GD-sAQa8Ru8GG5avMGOU9G98JtBcc3LQACLcBGAsYHQ/s693/sweet%2Bass%2Bflower.jpg" coords="753,66,70" shape="circle">
    <area target="_blank" alt="this guy is a fuckin mouthful" title="this guy is a fuckin mouthful" href="https://1.bp.blogspot.com/-zjfApMPySXs/Xy-i42eUVTI/AAAAAAAAAdI/jDve1BkGZ8AOvXr6EC_SlKBlQtcTrHfmACLcBGAsYHQ/s800/living%2Bfor%2Bthese%2Bvibes.jpg" coords="461,811,67" shape="circle">
    <area target="_blank" alt="wtf r u" title="wtf r u" href="https://1.bp.blogspot.com/-DjXnWw8Cujs/Xy-i7oi6dPI/AAAAAAAAAdM/fVc6BDpNNCMZLXQOEe5RH39qkhWaJpTogCLcBGAsYHQ/s944/wtf%2Bis%2Bthis.jpg" coords="988,232,83" shape="circle">
</map>

    </div>
</div>


</body>
</html>



<!--CONTENT GOES HERE-->

<?php include("tail.php");?>  <!-- Contact inf and end body/html tags->

